apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-kube-apiserver-operator
  namespace: {{ .Values.environmentName }}-test
  labels:
    platform/owner: {{ .Values.customerName }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-kube-apiserver-operator
      podSelector: 
        matchLabels:
          app: kube-apiserver-operator
  podSelector: {}
  policyTypes:
  - Ingress
